# Site settings
name: Deep Evolution
description: "the return to innocence"
url: "https://deev.ai"

avatar: yes
avatar_img_path: "imgs/logo.svg"


title: "Deep Evolution"



front_img: yes
front_img_path: "imgs/nautilus.png"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
